# Generated by Django 2.2.13 on 2020-06-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendreq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='detections'),
        ),
    ]
