# Generated by Django 2.2.13 on 2020-07-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendreq', '0002_auto_20200614_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detection',
            name='work_time',
            field=models.CharField(default='00:00:00', max_length=255),
        ),
    ]
