# Generated by Django 2.2.13 on 2020-07-04 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendreq', '0003_auto_20200704_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='work_time',
            field=models.TimeField(verbose_name=datetime.timedelta(0)),
        ),
    ]
