# Generated by Django 2.2.13 on 2020-07-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendreq', '0004_auto_20200704_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='work_time',
            field=models.CharField(default='00:00:00', max_length=11),
        ),
    ]
