# Generated by Django 2.2.13 on 2020-07-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendreq', '0006_auto_20200704_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
