# Generated by Django 2.2.13 on 2020-07-05 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendreq', '0008_auto_20200704_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='work_hours',
            field=models.TimeField(default=datetime.datetime(1900, 1, 1, 8, 0)),
        ),
    ]
