# Generated by Django 2.2.13 on 2020-07-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendreq', '0009_myuser_work_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='work_hours',
            field=models.CharField(default='08:00:00', max_length=11),
        ),
    ]
