# Generated by Django 2.2.13 on 2020-07-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendreq', '0010_auto_20200705_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='place',
            field=models.IntegerField(choices=[(1, 'Prishtine'), (2, 'Drenas'), (3, 'Ferizaj')]),
        ),
    ]
